# Exported from Render on 2026-03-25T10:17:20Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: ballons-translator-api
      runtime: python
      repo: https://github.com/shivaraj-arch/BallonsTranslator
      plan: free
      envVars:
      - key: PYTHON_VERSION
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: WORKERS
        sync: false
      - key: PORT
        sync: false
      region: singapore
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn api.server:app --host 0.0.0.0 --port $PORT
      healthCheckPath: /health
      autoDeployTrigger: "off"

